<script lang="ts">
	import type { Record } from '$lib/types/Record';
	import { onMount } from 'svelte';
	import Heatmap from 'visual-heatmap';
	import type { HeatmapRenderer } from 'visual-heatmap/dist/types/heatmap';

	export let className: string = '';

	export let record: Record;

	let container: HTMLElement;

	let heatmap: HeatmapRenderer | undefined;

	let isMounted: boolean = false;

	function updateHeatmap(): any {
		heatmap?.clear();
		heatmap = Heatmap('.surface', {
			size: 20.0,
			max: 1,
			min: 0,
			intensity: 1.0,
			gradient: [
				{
					color: [0, 0, 255, 1.0],
					offset: 0
				},
				{
					color: [0, 0, 255, 1.0],
					offset: 0.2
				},
				{
					color: [0, 255, 0, 1.0],
					offset: 0.45
				},
				{
					color: [255, 255, 0, 1.0],
					offset: 0.85
				},
				{
					color: [255, 0, 0, 1.0],
					offset: 1.0
				}
			]
		});

		// FIXME - canvas is generated by Heatmap... Cannot get a reference otherwise
		const canvas: HTMLCanvasElement = document.querySelector('canvas')!;
		canvas.style.width = '100%';
		canvas.style.height = '100%';
		canvas.width = canvas.offsetWidth;
		canvas.height = canvas.offsetHeight;
		const data = record.data
			?.flatMap((data) => data.touches.map((touch) => ({ x: touch.x, y: touch.y, value: 0.15 })))
			.map((elem) => ({ ...elem, x: elem.x * canvas.width, y: elem.y * canvas.height }));

		heatmap.clear();
		heatmap.renderData(data ?? []);
	}

	onMount(() => {
		isMounted = true;
		updateHeatmap();
	});

	$: record, isMounted && updateHeatmap();
</script>

<div class="container {className}" bind:this={container}>
	<div class="surface"></div>
</div>

<style>
	.container {
		margin-top: 1rem;
		width: calc(70vh * 9 / 16); /* 16:9 aspect ratio */
		height: 70vh;
		position: relative;
		background-color: rgba(255, 255, 255, 0.8);
		border-radius: 2px;
		box-shadow: none;
	}

	.surface {
		width: 100%;
		height: 100%;
	}
</style>
